version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build: 
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
