apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projet-cloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://projet-cloud-app.local"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
  - host: projet-cloud-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: projet-cloud-app-service
            port:
              number: 80
  - host: projet-cloud-back.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: projet-cloud-back-service
            port:
              number: 80