name: React-Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-front:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: cd front && npm ci

      - name: Build React app
        run: cd front && npm run build

  build-back:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: back/package-lock.json

      - name: Install dependencies
        run: cd back && npm ci

  docker:
    runs-on: self-hosted
    needs: [build-front, build-back]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for front-end
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-cloud-app:latest ./front
          docker push ${{ secrets.DOCKER_USERNAME }}/projet-cloud-app:latest

      - name: Build and push Docker images for back-end
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/projet-cloud-back:latest ./back
          docker push ${{ secrets.DOCKER_USERNAME }}/projet-cloud-back:latest

  kubernetes:
    runs-on: self-hosted
    needs: docker
    steps:
      - uses: actions/checkout@v3
  
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master
  
      - name: Deploy front-end and back-end to Kubernetes
        run: |
          kubectl apply -f infra/projet-cloud-app-deployment.yml
          kubectl apply -f infra/projet-cloud-back-server.yml
  
      - name: Apply Ingress configuration
        run: |
          kubectl apply -f infra/projet-cloud-ingress.yml
  
      - name: Check deployment
        run: |
          kubectl get pods
          kubectl get services
          kubectl get ingress