name: React-Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd front && npm install --package-lock-only

      - name: Build React app
        run: cd front && npm run build

  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: cd back && npm install --package-lock-only

  docker:
    runs-on: ubuntu-latest
    needs: [build-front, build-back]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/react-app:latest
            ${{ secrets.DOCKER_USERNAME }}/projet-cloud-back:latest

  kubernetes:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v3

      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/projet-cloud-app-deployment.yml
          kubectl apply -f infra/projet-cloud-back-server.yml

      - name: Check deployment
        run: |
          kubectl get pods
          kubectl get services
